branch-defaults:
  master:
    environment: sqso-test
    group_suffix: null
global:
  application_name: sqso-frontend
  branch: null
  default_ec2_keyname: sqso
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
